import {
  Bell,
  BookOpen,
  Home,
  LogIn,
  MessageCircle,
  PenTool,
  Settings,
  Share,
  Sparkles,
  Target,
  Trophy,
  User,
  Users,
} from 'lucide-react'

import { PATHS } from '../../_constants/paths'
import type { Category, NavigatorData, NavigatorItem } from '../_types/navigatorTypes'

export const screens: NavigatorItem[] = [
  {
    id: 'dashboard',
    title: 'ダッシュボード',
    description: '学習状況の概要と今日の目標',
    category: 'main',
    icon: Home,
    color: 'from-green-500 to-emerald-600',
    features: ['学習統計', '目標進捗', 'AIメッセージ'],
    href: PATHS.DASHBOARD,
  },
  {
    id: 'learning-records',
    title: '学習記録入力',
    description: '学習内容を記録してAIコメントを取得',
    category: 'study',
    icon: PenTool,
    color: 'from-emerald-500 to-teal-600',
    features: ['カテゴリ選択', '時間記録', 'AIコメント'],
    href: PATHS.LEARNING.RECORDS,
  },
  {
    id: 'sns-generator',
    title: 'SNS投稿作成',
    description: 'AIが学習記録から投稿文を自動生成',
    category: 'sns',
    icon: Share,
    color: 'from-teal-500 to-green-600',
    features: ['AI生成', 'トーン選択', 'ワンクリックシェア'],
    href: PATHS.SNS.GENERATOR,
  },
  {
    id: 'timeline',
    title: 'タイムライン',
    description: '仲間の学習記録を確認',
    category: 'community',
    icon: Users,
    color: 'from-emerald-500 to-green-600',
    features: ['投稿一覧', 'いいね・コメント', '検索機能'],
    href: PATHS.TIMELINE,
  },
  {
    id: 'ranking',
    title: 'ランキング',
    description: '学習時間でランキング表示',
    category: 'community',
    icon: Trophy,
    color: 'from-lime-500 to-emerald-600',
    features: ['日・週・月別', '順位変動', '表示ON/OFF'],
    href: PATHS.RANKING,
  },
  {
    id: 'my-page',
    title: 'マイページ',
    description: 'プロフィールと学習統計',
    category: 'profile',
    icon: User,
    color: 'from-teal-500 to-emerald-600',
    features: ['プロフィール', '統計', 'フォロー管理'],
    href: PATHS.MYPAGE,
  },
  {
    id: 'learning-style',
    title: '学習スタイル診断',
    description: 'あなたに合った学習仲間を発見',
    category: 'assessment',
    icon: Target,
    color: 'from-green-500 to-emerald-600',
    features: ['5つの質問', '3つのグループ', '仲間マッチング'],
    href: PATHS.LEARNING.STYLE,
  },
  {
    id: 'motivation-notification',
    title: 'モチベ通知',
    description: '仲間への励ましメッセージ',
    category: 'community',
    icon: MessageCircle,
    color: 'from-emerald-500 to-teal-600',
    features: ['グループ通知', '定型文', '通知履歴'],
    href: PATHS.NOTIFICATION.MOTIVATION,
  },
  {
    id: 'notification-settings',
    title: '通知設定',
    description: 'リマインダーと通知の管理',
    category: 'settings',
    icon: Bell,
    color: 'from-teal-500 to-green-600',
    features: ['リマインダー', '静音時間', '通知方法'],
    href: PATHS.NOTIFICATION.SETTINGS,
  },
  {
    id: 'auth',
    title: '認証画面',
    description: 'ログイン・サインアップ',
    category: 'auth',
    icon: LogIn,
    color: 'from-lime-500 to-green-600',
    features: ['ログイン', '新規登録', '機能紹介'],
    href: PATHS.AUTH.LOGIN,
  },
  {
    id: 'feature-showcase',
    title: '機能紹介',
    description: 'Manaboの全機能を紹介',
    category: 'info',
    icon: Sparkles,
    color: 'from-green-500 to-teal-600',
    features: ['機能一覧', 'ハイライト', '体験ガイド'],
    href: PATHS.INFO.FEATURE_SHOWCASE,
  },
]

export const categories: Category[] = [
  { id: 'all', label: 'すべて', icon: BookOpen },
  { id: 'main', label: 'メイン', icon: Home },
  { id: 'study', label: '学習', icon: PenTool },
  { id: 'sns', label: 'SNS', icon: Share },
  { id: 'community', label: 'コミュニティ', icon: Users },
  { id: 'profile', label: 'プロフィール', icon: User },
  { id: 'assessment', label: '診断', icon: Target },
  { id: 'settings', label: '設定', icon: Settings },
  { id: 'auth', label: '認証', icon: LogIn },
  { id: 'info', label: '情報', icon: Sparkles },
]

export const navigatorData: NavigatorData = {
  screens,
  categories,
}
