import { RankingPeriod, RankingUser } from '../_types/rankingTypes'

export const RANKING_DATA: Record<RankingPeriod, RankingUser[]> = {
  day: [
    {
      rank: 1,
      name: '山田 花子',
      avatar: 'YH',
      time: 8.5,
      streak: 25,
      change: '+2',
    },
    {
      rank: 2,
      name: '佐藤 太郎',
      avatar: 'ST',
      time: 7.2,
      streak: 18,
      change: '-1',
    },
    {
      rank: 3,
      name: 'あなた',
      avatar: '田',
      time: 6.8,
      streak: 15,
      change: '+1',
      isCurrentUser: true,
    },
    {
      rank: 4,
      name: '田中 美咲',
      avatar: 'TM',
      time: 6.5,
      streak: 12,
      change: '0',
    },
    {
      rank: 5,
      name: '鈴木 健太',
      avatar: 'SK',
      time: 5.9,
      streak: 8,
      change: '+3',
    },
  ],
  week: [
    {
      rank: 1,
      name: '佐藤 太郎',
      avatar: 'ST',
      time: 42.5,
      streak: 18,
      change: '+1',
    },
    {
      rank: 2,
      name: '山田 花子',
      avatar: 'YH',
      time: 38.2,
      streak: 25,
      change: '-1',
    },
    {
      rank: 3,
      name: 'あなた',
      avatar: '田',
      time: 35.5,
      streak: 15,
      change: '+2',
      isCurrentUser: true,
    },
    {
      rank: 4,
      name: '田中 美咲',
      avatar: 'TM',
      time: 32.8,
      streak: 12,
      change: '-1',
    },
    {
      rank: 5,
      name: '鈴木 健太',
      avatar: 'SK',
      time: 28.9,
      streak: 8,
      change: '+1',
    },
  ],
  month: [
    {
      rank: 1,
      name: '山田 花子',
      avatar: 'YH',
      time: 156.8,
      streak: 25,
      change: '0',
    },
    {
      rank: 2,
      name: '佐藤 太郎',
      avatar: 'ST',
      time: 142.3,
      streak: 18,
      change: '+1',
    },
    {
      rank: 3,
      name: '田中 美咲',
      avatar: 'TM',
      time: 128.5,
      streak: 12,
      change: '-1',
    },
    {
      rank: 4,
      name: 'あなた',
      avatar: '田',
      time: 125.2,
      streak: 15,
      change: '+3',
      isCurrentUser: true,
    },
    {
      rank: 5,
      name: '鈴木 健太',
      avatar: 'SK',
      time: 118.7,
      streak: 8,
      change: '-1',
    },
  ],
}
